# Generated by Django 6.0.2 on 2026-02-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(db_index=True, max_length=200)),
                ('prioridade', models.CharField(max_length=20)),
                ('status', models.IntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['prioridade'], name='core_tarefa_priorid_c275d7_idx')],
            },
        ),
    ]
