
import nbformat

notebook_data = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# Aula: Variáveis, Tipos de Dados e Entrada de Dados em Python\n",
                "\n",
                "Bem-vindos à nossa aula sobre os fundamentos da programação em Python! Hoje, vamos explorar conceitos essenciais que são a base para qualquer programa que você venha a desenvolver: **Variáveis**, **Tipos de Dados** e **Entrada de Dados**.\n",
                "\n",
                "## Objetivo da Aula\n",
                "Ao final desta aula, você será capaz de:\n",
                "\n",
                "*   Compreender o que são variáveis e como utilizá-las para armazenar informações.\n",
                "*   Identificar e trabalhar com os principais tipos de dados primitivos em Python (inteiros, decimais, textos e booleanos).\n",
                "*   Receber dados do usuário através da função `input()` e exibir informações com a função `print()`.\n",
                "*   Realizar a conversão de tipos de dados (casting) quando necessário.\n",
                "\n",
                "Vamos começar!"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 1. Tipos de Dados Primitivos\n",
                "\n",
                "Em Python, todo valor tem um tipo de dado. Conhecer os tipos de dados é fundamental para entender como o Python armazena e manipula as informações.\n",
                "\n",
                "### Inteiros (`int`)\n",
                "Representam números inteiros, positivos ou negativos, sem casas decimais.\n",
                "\n",
                "```python\n",
                "idade = 25\n",
                "quantidade = 100\n",
                "print(type(idade))\n",
                "print(type(quantidade))\n",
                "```\n",
                "\n",
                "### Números de Ponto Flutuante (`float`)\n",
                "Representam números reais, com casas decimais.\n",
                "\n",
                "```python\n",
                "altura = 1.75\n",
                "preco = 99.99\n",
                "print(type(altura))\n",
                "print(type(preco))\n",
                "```\n",
                "\n",
                "### Strings (`str`)\n",
                "Representam sequências de caracteres (texto). Podem ser definidas com aspas simples (`\'` ) ou aspas duplas (`\"`).\n",
                "\n",
                "```python\n",
                "nome = \"Alice\"\n",
                "mensagem = \'Olá, mundo!\'
",
                "print(type(nome))\n",
                "print(type(mensagem))\n",
                "```\n",
                "\n",
                "### Booleanos (`bool`)\n",
                "Representam valores lógicos: `True` (verdadeiro) ou `False` (falso). São muito usados em condições e tomadas de decisão.\n",
                "\n",
                "```python\n",
                "esta_chovendo = True\n",
                "tem_desconto = False\n",
                "print(type(esta_chovendo))\n",
                "print(type(tem_desconto))\n",
                "```\n",
                "\n",
                "---\n",
                "\n",
                "### Exercício 1: Identificação de Tipos de Dados\n",
                "\n",
                "**Objetivo:** Praticar a identificação dos tipos de dados primitivos em Python.\n",
                "\n",
                "**Instruções:** Para cada variável abaixo, adicione um comentário indicando qual é o seu tipo de dado (int, float, str, bool). Use a função `type()` para verificar se precisar.\n",
                "\n",
                "```python\n",
                "# Variável 1\n",
                "idade = 30\n",
                "# Tipo: int\n",
                "print(type(idade))\n",
                "\n",
                "# Variável 2\n",
                "preco = 19.99\n",
                "# Tipo: float\n",
                "print(type(preco))\n",
                "\n",
                "# Variável 3\n",
                "nome = \"Maria\"\n",
                "# Tipo: str\n",
                "print(type(nome))\n",
                "\n",
                "# Variável 4\n",
                "is_estudante = True\n",
                "# Tipo: bool\n",
                "print(type(is_estudante))\n",
                "\n",
                "# Variável 5\n",
                "numero_grande = 1000000\n",
                "# Tipo: int\n",
                "print(type(numero_grande))\n",
                "\n",
                "# Variável 6\n",
                "temperatura = -5.5\n",
                "# Tipo: float\n",
                "print(type(temperatura))\n",
                "\n",
                "# Variável 7\n",
                "mensagem = \"Olá, mundo!\"\n",
                "# Tipo: str\n",
                "print(type(mensagem))\n",
                "\n",
                "# Variável 8\n",
                "tem_desconto = False\n",
                "# Tipo: bool\n",
                "print(type(tem_desconto))\n",
                "```\n",
                "\n",
                "---\n",
                "\n",
                "## 2. Variáveis: Declaração e Uso\n",
                "\n",
                "Variáveis são como \"caixas\" ou \"contêineres\" que usamos para armazenar dados na memória do computador. Elas nos permitem dar nomes significativos aos valores, facilitando a leitura e manutenção do código.\n",
                "\n",
                "### Regras para Nomes de Variáveis em Python\n",
                "*   Devem começar com uma letra (a-z, A-Z) ou um underscore (`_`).\n",
                "*   Não podem começar com números.\n",
                "*   Podem conter letras, números e underscores.\n",
                "*   São *case-sensitive* (maiúsculas e minúsculas fazem diferença): `nome` é diferente de `Nome`.\n",
                "*   Não podem ser palavras reservadas do Python (ex: `if`, `else`, `for`, `while`, `print`, `input`).\n",
                "\n",
                "### Atribuição de Valores\n",
                "Usamos o operador de atribuição (`=`) para dar um valor a uma variável.\n",
                "\n",
                "```python\n",
                "nome_aluno = \"Carlos\"\n",
                "nota1 = 8.5\n",
                "nota2 = 7.0\n",
                "media = (nota1 + nota2) / 2\n",
                "print(f\"O aluno {nome_aluno} teve média {media}\")\n",
                "```\n",
                "\n",
                "### Reatribuição de Valores\n",
                "Você pode mudar o valor de uma variável a qualquer momento.\n",
                "\n",
                "```python\n",
                "contador = 0\n",
                "print(f\"Contador inicial: {contador}\")\n",
                "contador = contador + 1\n",
                "print(f\"Contador após incremento: {contador}\")\n",
                "contador = \"fim\" # Variáveis podem mudar de tipo em Python (tipagem dinâmica)\n",
                "print(f\"Contador agora é: {contador}\")\n",
                "```\n",
                "\n",
                "### Diferença entre Constantes e Variáveis (Convenções em Python)\n",
                "Python não tem um conceito de \"constante\" como em outras linguagens (onde o valor não pode ser alterado depois de definido). No entanto, por **convenção**, usamos nomes de variáveis em **MAIÚSCULAS** para indicar que elas devem ser tratadas como constantes, ou seja, seus valores não devem ser alterados durante a execução do programa.\n",
                "\n",
                "```python\n",
                "PI = 3.14159\n",
                "TAXA_JUROS = 0.05\n",
                "\n",
                "print(f\"Valor de PI: {PI}\")\n",
                "print(f\"Taxa de Juros: {TAXA_JUROS}\")\n",
                "\n",
                "# Embora seja possível, evite reatribuir constantes por convenção\n",
                "# PI = 3.0 # Não faça isso em um código real se PI for uma constante\n",
                "```\n",
                "\n",
                "---\n",
                "\n",
                "### Exercício 2: Declaração e Manipulação de Variáveis\n",
                "\n",
                "**Objetivo:** Praticar a declaração, atribuição e reatribuição de valores a variáveis.\n",
                "\n",
                "**Instruções:**\n",
                "1. Declare uma variável `cidade` e atribua a ela o nome da sua cidade.\n",
                "2. Declare uma variável `populacao` e atribua a ela um valor numérico (aproximado) da população da sua cidade.\n",
                "3. Imprima o valor de ambas as variáveis.\n",
                "4. Reatribua a variável `cidade` para o nome de outra cidade.\n",
                "5. Reatribua a variável `populacao` para um novo valor.\n",
                "6. Imprima os novos valores das variáveis.\n",
                "\n",
                "```python\n",
                "# Seu código aqui\n",
                "cidade = \"São Paulo\"\n",
                "populacao = 12000000\n",
                "print(f\"Cidade: {cidade}, População: {populacao}\")\n",
                "\n",
                "cidade = \"Rio de Janeiro\"\n",
                "populacao = 6700000\n",
                "print(f\"Nova Cidade: {cidade}, Nova População: {populacao}\")\n",
                "```\n",
                "\n",
                "---\n",
                "\n",
                "## 3. Entrada e Saída de Dados\n",
                "\n",
                "Para que nossos programas sejam interativos, precisamos de formas de exibir informações para o usuário (saída) e de receber informações dele (entrada).\n",
                "\n",
                "### Função `print()` para Saída de Dados\n",
                "A função `print()` é usada para exibir mensagens e valores na tela.\n",
                "\n",
                "```python\n",
                "print(\"Olá, Python!\")\n",
                "\n",
                "nome = \"Ana\"\n",
                "idade = 28\n",
                "\n",
                "# Imprimindo variáveis\n",
                "print(nome)\n",
                "print(idade)\n",
                "\n",
                "# Concatenação de strings (não recomendado para muitas variáveis)\n",
                "print(\"Meu nome é \" + nome + \" e tenho \" + str(idade) + \" anos.\")\n",
                "\n",
                "# F-strings (formatar strings) - RECOMENDADO!\n",
                "print(f\"Meu nome é {nome} e tenho {idade} anos.\")\n",
                "\n",
                "# Múltiplos argumentos para print (separados por espaço por padrão)\n",
                "print(\"Nome:\", nome, \"Idade:\", idade)\n",
                "```\n",
                "\n",
                "### Função `input()` para Entrada de Dados\n",
                "A função `input()` é usada para receber dados digitados pelo usuário. **Importante:** `input()` sempre retorna o valor como uma **string**.\n",
                "\n",
                "```python\n",
                "# Exemplo básico\n",
                "nome_usuario = input(\"Digite seu nome: \")\n",
                "print(f\"Bem-vindo(a), {nome_usuario}!\")\n",
                "\n",
                "# Recebendo um número (ainda como string!)\n",
                "numero_str = input(\"Digite um número: \")\n",
                "print(f\"Você digitou: {numero_str}, que é do tipo: {type(numero_str)}\")\n",
                "```\n",
                "\n",
                "---\n",
                "\n",
                "### Exercício 3: Entrada e Saída de Dados\n",
                "\n",
                "**Objetivo:** Utilizar as funções `input()` e `print()` para interagir com o usuário.\n",
                "\n",
                "**Instruções:**\n",
                "1. Peça ao usuário para digitar seu nome e armazene-o em uma variável `seu_nome`.\n",
                "2. Peça ao usuário para digitar sua idade e armazene-a em uma variável `sua_idade`.\n",
                "3. Usando f-strings, imprima uma mensagem personalizada que inclua o nome e a idade digitados pelo usuário.\n",
                "   Exemplo: \"Olá, [seu_nome]! Você tem [sua_idade] anos.\"\n",
                "\n",
                "```python\n",
                "# Seu código aqui\n",
                "seu_nome = input(\"Digite seu nome: \")\n",
                "sua_idade = input(\"Digite sua idade: \")\n",
                "print(f\"Olá, {seu_nome}! Você tem {sua_idade} anos.\")\n",
                "```\n",
                "\n",
                "---\n",
                "\n",
                "## 4. Casting de Dados\n",
                "\n",
                "Como vimos, a função `input()` sempre retorna uma string. Mas e se precisarmos fazer cálculos com os números que o usuário digitou? Precisamos converter (ou fazer o \"casting\") essa string para um tipo numérico (inteiro ou float).\n",
                "\n",
                "### Funções de Conversão\n",
                "*   `int()`: Converte para inteiro.\n",
                "*   `float()`: Converte para número de ponto flutuante.\n",
                "*   `str()`: Converte para string.\n",
                "*   `bool()`: Converte para booleano.\n",
                "\n",
                "```python\n",
                "# Exemplo de conversão de string para int\n",
                "numero_str = \"123\"\n",
                "numero_int = int(numero_str)\n",
                "print(f\"\\\'{numero_str}\\\' (tipo: {type(numero_str)}) convertido para {numero_int} (tipo: {type(numero_int)}))\")\n",
                "\n",
                "# Exemplo de conversão de string para float\n",
                "valor_str = \"45.67\"\n",
                "valor_float = float(valor_str)\n",
                "print(f\"\\\'{valor_str}\\\' (tipo: {type(valor_str)}) convertido para {valor_float} (tipo: {type(valor_float)}))\")\n",
                "\n",
                "# Exemplo de uso com input()\n",
                "num1_str = input(\"Digite o primeiro número: \")\n",
                "num2_str = input(\"Digite o segundo número: \")\n",
                "\n",
                "num1 = int(num1_str)\n",
                "num2 = int(num2_str)\n",
                "\n",
                "soma = num1 + num2\n",
                "print(f\"A soma é: {soma}\")\n",
                "\n",
                "# Cuidado com erros de conversão!\n",
                "# int(\"abc\") # Isso geraria um erro!\n",
                "```\n",
                "\n",
                "---\n",
                "\n",
                "### Exercício 4: Casting de Dados\n",
                "\n",
                "**Objetivo:** Praticar a conversão de tipos de dados (casting).\n",
                "\n",
                "**Instruções:**\n",
                "1. Peça ao usuário para digitar dois números inteiros e armazene-os em variáveis (lembre-se que `input()` retorna string).\n",
                "2. Converta essas strings para números inteiros.\n",
                "3. Calcule a soma, subtração, multiplicação e divisão desses dois números.\n",
                "4. Imprima os resultados de cada operação, indicando qual operação foi realizada.\n",
                "\n",
                "```python\n",
                "# Seu código aqui\n",
                "num1_str = input(\"Digite o primeiro número inteiro: \")\n",
                "num2_str = input(\"Digite o segundo número inteiro: \")\n",
                "\n",
                "num1 = int(num1_str)\n",
                "num2 = int(num2_str)\n",
                "\n",
                "soma = num1 + num2\n",
                "subtracao = num1 - num2\n",
                "multiplicacao = num1 * num2\n",
                "divisao = num1 / num2 # A divisão sempre retorna um float\n",
                "\n",
                "print(f\"Soma: {soma}\")\n",
                "print(f\"Subtração: {subtracao}\")\n",
                "print(f\"Multiplicação: {multiplicacao}\")\n",
                "print(f\"Divisão: {divisao}\")\n",
                "```\n",
                "\n",
                "---\n",
                "\n",
                "### Exercício 5: Desafio Combinado\n",
                "\n",
                "**Objetivo:** Combinar os conceitos de variáveis, entrada/saída e casting.\n",
                "\n",
                "**Instruções:**\n",
                "1. Peça ao usuário para digitar o preço de um produto e a quantidade comprada.\n",
                "2. Calcule o valor total da compra.\n",
                "3. Peça ao usuário para digitar o valor pago.\n",
                "4. Calcule o troco.\n",
                "5. Imprima o valor total da compra e o troco de forma formatada.\n",
                "\n",
                "```python\n",
                "# Seu código aqui\n",
                "preco_str = input(\"Digite o preço do produto: \")\n",
                "quantidade_str = input(\"Digite a quantidade comprada: \")\n",
                "\n",
                "preco = float(preco_str)\n",
                "quantidade = int(quantidade_str)\n",
                "\n",
                "valor_total = preco * quantidade\n",
                "print(f\"Valor total da compra: R$ {valor_total:.2f}\")\n",
                "\n",
                "valor_pago_str = input(\"Digite o valor pago: \")\n",
                "valor_pago = float(valor_pago_str)\n",
                "\n",
                "troco = valor_pago - valor_total\n",
                "print(f\"Troco: R$ {troco:.2f}\")\n",
                "```\n",
                "\n",
                "---\n",
                "\n",
                "## Conclusão\n",
                "\n",
                "Parabéns! Você concluiu a primeira parte da nossa jornada em Python. Hoje, você aprendeu sobre:\n",
                "\n",
                "*   **Tipos de Dados Primitivos:** `int`, `float`, `str`, `bool`\n",
                "*   **Variáveis:** Como declarar, usar e a diferença entre variáveis e \"constantes\" (por convenção).\n",
                "*   **Entrada e Saída de Dados:** Usando `print()` para exibir e `input()` para receber informações.\n",
                "*   **Casting de Dados:** Convertendo tipos com `int()`, `float()`, `str()`, etc.\n",
                "\n",
                "Estes são conceitos fundamentais que você usará em praticamente todos os programas que escrever. Continue praticando e explorando!\n",
                "\n",
                "Se tiver dúvidas, revise o material e os exercícios. Até a próxima!\n",
                "\n",
                """
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "---\n",
                "\n",
                "### Exercício Extra: Calculadora Simples\n",
                "\n",
                "**Objetivo:** Criar uma calculadora simples que receba dois números e uma operação, e exiba o resultado.\n",
                "\n",
                "**Instruções:**\n",
                "1. Peça ao usuário para digitar o primeiro número.\n",
                "2. Peça ao usuário para digitar o segundo número.\n",
                "3. Peça ao usuário para digitar a operação desejada (ex: \'+\', \'-\' , \'*\', \'/\').\n",
                "4. Realize a operação e imprima o resultado. Lembre-se de converter os números para o tipo correto antes de realizar a operação.\n",
                "\n",
                "```python\n",
                "# Seu código aqui\n",
                "num1_str = input(\"Digite o primeiro número: \")\n",
                "num2_str = input(\"Digite o segundo número: \")\n",
                "operacao = input(\"Digite a operação (+, -, *, /): \")\n",
                "\n",
                "num1 = float(num1_str)\n",
                "num2 = float(num2_str)\n",
                "\n",
                "if operacao == \'+\':\n",
                "    resultado = num1 + num2\n",
                "elif operacao == \'-\' :\n",
                "    resultado = num1 - num2\n",
                "elif operacao == \'*\':\n",
                "    resultado = num1 * num2\n",
                "elif operacao == \'/\':\n",
                "    if num2 != 0:\n",
                "        resultado = num1 / num2\n",
                "    else:\n",
                "        resultado = \"Erro: Divisão por zero!\"\n",
                "else:\n",
                "    resultado = \"Operação inválida!\"\n",
                "\n",
                "print(f\"Resultado: {resultado}\")\n",
                "```\n"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "---\n",
                "\n",
                "### Exercício 6: Conversão de Temperatura\n",
                "\n",
                "**Objetivo:** Converter uma temperatura de Celsius para Fahrenheit usando casting.\n",
                "\n",
                "**Instruções:**\n",
                "1. Peça ao usuário para digitar uma temperatura em Celsius (número decimal).\n",
                "2. Converta a entrada para o tipo `float`.\n",
                "3. Calcule a temperatura em Fahrenheit usando a fórmula: `Fahrenheit = (Celsius * 9/5) + 32`.\n",
                "4. Imprima o resultado formatado com duas casas decimais.\n",
                "\n",
                "```python\n",
                "# Seu código aqui\n",
                "celsius_str = input(\"Digite a temperatura em Celsius: \")\n",
                "celsius = float(celsius_str)\n",
                "fahrenheit = (celsius * 9/5) + 32\n",
                "print(f\"A temperatura em Fahrenheit é: {fahrenheit:.2f}F\")\n",
                "```\n",
                "\n",
                "---\n",
                "\n",
                "### Exercício 7: Análise de Dados de Usuário\n",
                "\n",
                "**Objetivo:** Coletar diferentes tipos de dados do usuário e garantir que estejam nos formatos corretos.\n",
                "\n",
                "**Instruções:**\n",
                "1. Peça ao usuário para digitar seu nome completo.\n",
                "2. Peça ao usuário para digitar o ano de seu nascimento.\n",
                "3. Peça ao usuário para digitar sua altura em metros (ex: 1.75).\n",
                "4. Converta o ano de nascimento para `int` e a altura para `float`.\n",
                "5. Calcule a idade aproximada do usuário (ano atual - ano de nascimento).\n",
                "6. Imprima todas as informações coletadas e calculadas, incluindo os tipos de dados de cada variável após o casting.\n",
                "\n",
                "```python\n",
                "# Seu código aqui\n",
                "nome_completo = input(\"Digite seu nome completo: \")\n",
                "ano_nascimento_str = input(\"Digite o ano de seu nascimento: \")\n",
                "altura_str = input(\"Digite sua altura em metros (ex: 1.75): \")\n",
                "\n",
                "ano_nascimento = int(ano_nascimento_str)\n",
                "altura = float(altura_str)\n",
                "\n",
                "import datetime\n",
                "ano_atual = datetime.datetime.now().year\n",
                "idade = ano_atual - ano_nascimento\n",
                "\n",
                "print(f\"Nome: {nome_completo} (Tipo: {type(nome_completo)})\")\n",
                "print(f\"Ano de Nascimento: {ano_nascimento} (Tipo: {type(ano_nascimento)})\")\n",
                "print(f\"Altura: {altura} (Tipo: {type(altura)})\")\n",
                "print(f\"Idade aproximada: {idade} anos\")\n",
                "```\n",
                "\n",
                "---\n",
                "\n",
                "### Exercício 8: Soma Segura de Números\n",
                "\n",
                "**Objetivo:** Receber dois números do usuário e somá-los, tratando possíveis erros de conversão.\n",
                "\n",
                "**Instruções:**\n",
                "1. Peça ao usuário para digitar o primeiro número.\n",
                "2. Peça ao usuário para digitar o segundo número.\n",
                "3. Tente converter ambos para `float` e some-os.\n",
                "4. Se a conversão falhar (por exemplo, se o usuário digitar texto), imprima uma mensagem de erro amigável. (Dica: use um bloco `try-except` se já tiver aprendido, caso contrário, apenas comente sobre o erro).\n",
                "5. Imprima o resultado da soma ou a mensagem de erro.\n",
                "\n",
                "```python\n",
                "# Seu código aqui\n",
                "num1_str = input(\"Digite o primeiro número: \")\n",
                "num2_str = input(\"Digite o segundo número: \")\n",
                "\n",
                "try:\n",
                "    num1 = float(num1_str)\n",
                "    num2 = float(num2_str)\n",
                "    soma = num1 + num2\n",
                "    print(f\"A soma é: {soma}\")\n",
                "except ValueError:\n",
                "    print(\"Erro: Por favor, digite apenas números válidos.\")\n",
                "```\n"
            ]
        }
    ],
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "codemirror_mode": {
                "name": "ipython",
                "version": 3
            },
            "file_extension": ".py",
            "mimetype": "text/x-python",
            "name": "python",
            "nbconvert_exporter": "python",
            "pygments_lexer": "ipython3",
            "version": "3.11.0"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 4
}

# Cria um objeto notebook a partir do dicionário
nb = nbformat.from_dict(notebook_data)

# Salva o notebook em um novo arquivo
with open("aula_variaveis_tipos_dados_final.ipynb", "w", encoding="utf-8") as f:
    nbformat.write(nb, f)

print("Arquivo aula_variaveis_tipos_dados_final.ipynb gerado com sucesso.")


